<?php
require $_SERVER['DOCUMENT_ROOT'] . '/RS/include/db.php';
require $_SERVER['DOCUMENT_ROOT'] . '/RS/vendor/setasign/fpdf/fpdf.php';

$id = $_GET['id'] ?? null; // Ambil ID dokter dari parameter URL
$dokter = id_dokter($id); // Fungsi untuk mengambil data dokter dari database

if (!$dokter) {
    die("Data dokter tidak ditemukan.");
}

// Inisialisasi PDF
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Helvetica', 'B', 18);
$pdf->SetTextColor(33, 37, 41); 

// Judul PDF
$pdf->Cell(190, 12, 'Detail Dokter', 0, 1, 'C');
$pdf->Ln(5);

// Garis pemisah
$pdf->SetLineWidth(0.5);
$pdf->SetDrawColor(100, 100, 100);
$pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY()); 
$pdf->Ln(8);

// Set font dan warna untuk konten
$pdf->SetFont('Helvetica', '', 12);
$pdf->SetFillColor(230, 230, 230); 

// Data dokter yang akan ditampilkan
$fields = [
    'Nama' => $dokter['nama'],
    'Tanggal Lahir' => $dokter['tanggal_lahir'],
    'Jenis Kelamin' => $dokter['jenis_kelamin'],
    'Agama' => $dokter['agama'],
    'Spesialisasi' => $dokter['spesialisasi']
];

// Loop untuk menampilkan data
foreach ($fields as $label => $value) {
    $pdf->Cell(50, 10, $label, 1, 0, 'L', true); // Kolom label
    $pdf->Cell(140, 10, $value, 1, 1, 'L'); // Kolom nilai
}

// Menampilkan foto jika ada
if (!empty($dokter['foto'])) {
    $foto_path = $_SERVER['DOCUMENT_ROOT'] . '/RS/uploads/' . $dokter['foto'];
    if (file_exists($foto_path)) {
        $pdf->Ln(10); // Spasi sebelum foto
        $pdf->Cell(190, 10, 'Foto Dokter', 0, 1, 'C'); // Judul foto
        $pdf->Image($foto_path, 80, $pdf->GetY(), 50, 50); // Menampilkan foto
        $pdf->Ln(55); // Spasi setelah foto
    }
}

// Footer PDF
$pdf->Ln(10);
$pdf->SetFont('Helvetica', 'I', 10);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(190, 10, 'Generated by Rumah Sakit Al - ' . date('d M Y'), 0, 1, 'C');

// Output PDF
$pdf->Output('D', 'Dokter_' . $dokter['nama'] . '.pdf'); // Download file PDF dengan nama sesuai nama dokter
?>